### ISSUE TITLE
Feature to remove YT-Shorts from my Subscriptions Page (or maybe everywhere)

### ISSUE THREAD

**Issue by lucasra1** [Compile-Time/yt-quick-actions#1]

**Comment by Compile-Time** [comment]
Hi, I think such a feature would not fit conceptually for this extension. The name of the extension
implies that this extension provides quicker access to actions that are available on YouTube.
Therefore, being able to hide YouTube shorts feels very out of place.

However, there exists an extension that can do that for you: [Enhancer for YouTube](https://www.mrfdev.com/enhancer-for-youtube)

On Chrome simply toggle the `Hide Shorts` option in the settings.
![enhancer_for_youtube_setting](https://user-images.githubusercontent.com/18414241/205969582-a4075753-0200-47d7-847f-a2a934a5d16a.png)


On Firefox toggle the option and set a config flag in `about:config`.
> (Firefox 103+ and "layout.css.has-selector.enabled" set to "true" - Experimental CSS feature not fully working on Firefox, some rendering issues may occur!)

![firefox_config_flag](https://user-images.githubusercontent.com/18414241/205969590-06895479-c1b7-45fa-b3af-222aebf929f8.png)

I hope this is helpful for you :slightly_smiling_face:
