### ISSUE TITLE
Delete not working on german YT

### ISSUE THREAD

**Issue by FlorianFeka** [Compile-Time/yt-quick-actions#2]
**Bug**

Clicking trash icon in the menu opens context menu.

![image](https://user-images.githubusercontent.com/47530143/210284505-53a3c739-b6db-420f-b437-414fe336f03a.png)

**Possible Fix**

Check on Trash Icon Path `/html/body/ytd-app/ytd-popup-container/tp-yt-iron-dropdown/div/ytd-menu-popup-renderer/tp-yt-paper-listbox/ytd-menu-service-item-renderer[4]/tp-yt-paper-item/yt-icon/svg/g/path`

**Comment by Compile-Time** [comment]
Thanks for the report and hint! Sorry for this major oversight :disappointed:

**Comment by Compile-Time** [comment]
Closing: This is now fixed in the 1.0.1 release. If you still have any problems, feel free to re-open the issue.
