### ISSUE TITLE
[Feature idea] Add a "Watch later" button for YT Shorts

### ISSUE THREAD

**Issue by StefanTirea** [Compile-Time/yt-quick-actions#3]
Currently there is no easy way to add a Youtube Shorts video to a playlist.
My idea would be to add a button in the actions row or in the dropdown where the video can be added to the watch later playlist via one click.

Current UI of YT Shorts + possible locations:
![image](https://user-images.githubusercontent.com/19685364/211127090-e3c83205-4e3c-404c-bcf3-b827801b7251.png)

**Comment by Compile-Time** [comment]
Hi, overall this idea would fit very well into the extension. However, it might take some time to get this to work or at worst it might not be possible to implement. Currently, the extension re-uses actions that already exists on a page which allows it to function without any API keys. Since shorts do not have a watch later action present, a new approach needs to be determined.

I have a rough idea in mind on how to maybe solve this, however, it will take some time.

**Comment by StefanTirea** [comment]
Ok, looked into possible solutions:

❌**Youtube Data API:**
For this the user has to login with a google account so the extension can work on behalf the user (OAuth2). However, an API key is also required, which is rate limited to 10 000 units. Inserting a video into a playlist costs [50 units](https://developers.google.com/youtube/v3/determine_quota_cost#playlistItems). Therefore, only 200 requests would be possible, which will quickly break when more than 30 users are using this feature.

✅**Trigger actions via the website**:
Similar to your approach, use the website itself to trigger actions. I reverse engineered how videos are added to playlists:
* https://www.youtube.com/youtubei/v1/browse/edit_playlist?key=<key>&prettyPrint=false
* Header with many tokens & keys
* The request body contains:
  * `context`: various information about the user
  * `actions`: contains what action is triggered on this endpoint (ADD, DELETE, ...) + the video id from the url
  * `playlistId`: playlist name (for Watch Later => `WL`)
 
The best approach that worked for me is to use a different action, for example the `LIKE` video action, and catch + mutate this request to contain all the playlist information. Following must be changed for a working solution:
* Change url to the `playlist` url but keep the request parameter `key` from the `like` url
* Append to json body: `"actions": [{ "addedVideoId": "<video-id>", "action": "ACTION_ADD_VIDEO" }],"playlistId": "WL",`
* Update the `content-length` in the header to the correct value

I will try to implement a working prototype for your extension in the coming days.
