### ISSUE TITLE
Tweak Prettier settings

### ISSUE THREAD

**Issue by Compile-Time** [Compile-Time/yt-quick-actions#9]
Go over the source code and check the formatting for cases that could be improved / don't look so good.

So far, I noticed the following:
- Inconsistent line breaks for `HtmlTreeNavigator.filter()` calls.
  https://github.com/Compile-Time/yt-quick-actions/blob/30bc3745fe524e2a3e1e8de07957418df3e90667/src/content_scripts/pages/video.ts#L77).
  This is most likely related to the line width limit.

**Comment by lucasra1** [comment]
Yeah i forgot about that. maybe change the line width to `150`.
https://prettier.io/docs/en/options.html#print-width
